# .streamlit/secrets.toml

[mysql]
host = "localhost"          # Or your cloud DB host
port = 3306
database = "atliq_tshirts"
username = "root"
password = "root"

[api_keys]
GEMINI_API_KEY = "your_gemini_api_key_here"
